### ISSUE TITLE
Json to Model deserializer has element type issue

### ISSUE THREAD

**Issue by natgmac** [hypar-io/elements#101]
If a new element is added to a hypar model and given a new type (ex. "VAV"), then converted into a JSON, an issue occurs when you attempt to deserialize it. This error occurs.

https://github.com/hypar-io/elements/blob/19e6a752543c3003924888f3ee7c22190925575c/src/Elements/Serialization/ElementConverter.cs#L81

It's likely coming from here, where its referencing the list of acceptable element types. "VAV" may not be in the acceptable list and therefore throws the error.

https://github.com/hypar-io/elements/blob/19e6a752543c3003924888f3ee7c22190925575c/src/Elements/Serialization/ElementConverter.cs#L27

@wynged has also been digging into it.

**Comment by wynged** [comment]
heyo.
I thought that using code something like this would help.  Searching all loaded assemblies for IElements rather than just the currently running assembly.  Would help if people want to make their own classes that implement IElement or inherit from Element.
``` C#
foreach (var assembly in  AppDomain.CurrentDomain.GetAssemblies())
{
 _elementTypes.AddRange(assembly.GetTypes().Where(t=>typeof(IElement).IsAssignableFrom(t)).ToList());
}
```
but couldn't get a successful test due to not knowing how to property reference a custom built Hypar.Elements.  When I tested on an elements.csproj locally I lost the Hypar.Geometry namespace.

**Comment by wynged** [comment]
Awesome, will try to make the changes in the next few days.

**Comment by ikeough** [comment]
This is now addressed in #113.

**Comment by wynged** [comment]
Great, thanks for doing this.

**Comment by ikeough** [comment]
I believe this is closed with the above-referenced commit.
