### ISSUE TITLE
Elements needs a live reloading viewer for local testing.

### ISSUE THREAD

**Issue by ikeough** [hypar-io/Elements#108]
Live reloading is well-trodden territory in the node world, but we cannot assume that users will have, or will want to have, node on their machines. Therefore, we probably can't rely on existing solutions that require npm packages. 

Is it possible to build a very simple live reloading viewer using dotnet so that users can visualize the output of their elements work locally?

There's a couple options for how we could do this:
- Generate static pages during `dotnet test` that show the model created during testing. The `ModelTest` base class could include this generation in its dispose method, in the same way that it currently generates `.glb` and `.json` files. Running `dotnet test` would, in addition to running the tests, generate a folder hierarchy of test names, pages, and models, and possibly an index page.
  - This would help us ultimately with the documentation story as well as tests could be used to generate documentation with live 3d visuals.
- Make a separate nuget called `Elements.View` that is a [dotnet global tool](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools). The tool will have a very simple web server that serves a page with a threejs viewer and a gltf loader that points to a file location. The user does `dotnet elements view` and gets a message to visit localhost:xxxxx.
  - The challenge here is where we point to get the model. With a static page the url of the gltf file will need to be hard coded. The user will therefore be responsible for making sure that a gltf file shows up in the right place.
- The third way, which would be some combination of the first two would be to build a Visual Studio Code extension that allows you to write scripts and visualize, in a second panel, the geometry, in real time.

**Comment by radumg** [comment]
> * The third way, which would be some combination of the first two would be to build a Visual Studio Code extension that allows you to write scripts and visualize, in a second panel, the geometry, in real time.

The third way would definitely be awesome, it has two `but`s however : 
- Assumes VS Code, some would still be using VS proper (could be preference or because they have to)
- requires the first 2 anyway, so maybe it's a `later` improvement?

> * Make a separate nuget called `Elements.View` that is a [dotnet global tool](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools). The tool will have a very simple web server that serves a page with a threejs viewer and a gltf loader that points to a file location. The user does `dotnet elements view` and gets a message to visit localhost:xxxxx.

yes please 😍, this is what we had in mind to make as well.

>   * The challenge here is where we point to get the model. With a static page the url of the gltf file will need to be hard coded. The user will therefore be responsible for making sure that a gltf file shows up in the right place.

What if the file location could be supplied after the viewer started, maybe as a query parameter `localhost:xxxx/view?file=pathToFile.gltf`? The server serving the page (let's assume ASP .NET Core, Nancy, NodeJS or similar) would monitor the filesystem for any changes to this specified file, so it reloads whenever it changes (on build for example).

Yes, the user would still be responsible for creating the `.gltf`, but if that was generated as part of a `test` or something like that, it could be easy.

Which brings to mind, if unit tests automatically generated `gltf` files as a by-product, you could simply `dotnet elements view name-of-test`, which runs the test (creating a gltf), then monitors for source-file change and re-runs as necessary. Not sure if I explained it well enough - it's similar to how the VisualStudio test explorer works now.

**Comment by ikeough** [comment]
We've got the first inklings of this working by separating the Typescript stuff that defines the 3D view into a separate node package, and building a live-reloading server using the webpack dev tools. As much as I want to do this all in the dotnet space, all the tooling for node just makes it too easy. Also, reusing the exact assets from the app, so any improvements made to this viewer, will end up in the app.

Here's the first [demo](https://twitter.com/HyparAEC/status/1104442712298680320). 

This will also further the conversation we've been having with @drajmarsh.

**Comment by radumg** [comment]
Great ! Let us know if/where the repo is and we'll sure start using it as early as this coming week.

**Comment by ikeough** [comment]
https://github.com/hypar-io/function#previewing

**Comment by ikeough** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Live Reloading Visualizer](https://trello.com/c/YPrkf5Nx/4-live-reloading-visualizer)

**Comment by andrewheumann** [comment]
I think we can close this, no?

**Comment by ikeough** [comment]
I do believe we can!
