### ISSUE TITLE
Provide AddOpenings method on Floor

### ISSUE THREAD

**Issue by simonmoreau** [hypar-io/Elements#139]
I am trying to build a Staircase element that create an opening in every floors it pass through.

To do so, I need to be able to create an opening in an existing floor, but from my understanding, an opening can only be added when creating the floor.

This new AddOpenings method would update the geometry of the floor without changing its other properties (Profile, FloorType, ...).

**Comment by radumg** [comment]
To add to this, we're currently debating ( @markthorley ) whether to

- internally add an `UpdateProfile` method for floors
- or if we should re-build the floor

This is to handle situations when an existing building is re-designed, such as making a floor step back.
It'd certainly be easier for us to work with a method vs rebuild, as relationships between elements start to entangle.

Let us know if this is something desirable to add back to `Hypar.Elements` @ikeough .

**Comment by ikeough** [comment]
@simonmoreau Stairs! Very excited. Will you contribute your `Stair` type to Elements? The reason I ask is because we'd be happy to do the work to serialize stairs to IFC. You'll note that on the `README`, I've started an IFC mapping table. I'll be filling in the holes in that table over time.

We now have the interface `IHasOpenings` which specifies that an Element contains a number of associated openings. Your stair could have one `Opening` which defines its plan area, and associated `Floors` could have this `Opening` in their `Openings` collection so that when they get rendered, the stairs punch through the `Floor`.

In recent versions of Elements, we've move solid geometry calculation from the constructors to the stage right before stuff gets exported to glTF so the `Floor` geometry _should_ get calculated correctly if you do as above.

**Comment by simonmoreau** [comment]
@ikeough My `stair` class is not yet ready to be published, but I will create a pull request when I have something presentable.

For the opening, I can't add them to the `Openings` collection, some of the floor don't have any opening when created and the collection is still null :

```
            Polygon openingPolygon = Polygon.Rectangle(width, height);
            Opening opening = new Opening(openingPolygon);

            List<Floor> floors = _model.ElementsOfType<Floor>().ToList();
            foreach (Floor floor in floors)
            {
                floor.Openings.Append(opening); // System.ArgumentNullException : Value cannot be null.
            }
```
Maybe we should create an empty array of Openings even if there is no opening upon creating the floor.

**Comment by ikeough** [comment]
Yes. That's exactly what's happening. I've added #142 for this.

**Comment by simonmoreau** [comment]
Great! Do you mind me sending a pull request for this?

**Comment by ikeough** [comment]
Not at all. I ❤️ pull requests.
